ALTER TABLE restaurant_settings ADD COLUMN IF NOT EXISTS instagram TEXT NOT NULL DEFAULT '';
ALTER TABLE restaurant_settings ADD COLUMN IF NOT EXISTS telegram TEXT NOT NULL DEFAULT '';
ALTER TABLE restaurant_settings ADD COLUMN IF NOT EXISTS tiktok TEXT NOT NULL DEFAULT '';
ALTER TABLE restaurant_settings ADD COLUMN IF NOT EXISTS youtube TEXT NOT NULL DEFAULT '';
